M48
; DRILL file {KiCad 7.0.9} date Sun Nov 26 00:13:22 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-26T00:13:22+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X128.62Y-104.91
T1
X128.62Y-97.86G85X128.62Y-97.56
G05
T0
M30
